### ISSUE TITLE
Issues with autoplay and videos on the Cannabist.

### ISSUE THREAD

**Issue by freejoe76** [denverpost/dptv#163]
When I click on this link for The Cannabist Show from DPTV homepage, the page loads and video plays for about 1 second before it reloads again as a Photo Night post and then it switches to 420 Tours video -- the next posts that follow The Cannabist Show.

**Comment by AletaLabak** [comment]
Here's the URL, and a note
http://dptv.denverpost.com/2015/03/11/the-cannabist-show-march-11-2015/

So I was having the problem at home, tried it multiple times. But now when I have this link open in the office, the video is playing properly. Wonder why there's this difference.

**Comment by freejoe76** [comment]
Another note:
We've been able to replicate this problem. Can you please take a look? It happens on the cannabist article page after you hit play and the ad is over:

http://dptv.denverpost.com/2015/03/11/the-cannabist-show-march-11-2015/

**Comment by freejoe76** [comment]
I was able to replicate this issue for the first three videos I played on DPTV, and then it stopped doing that.

**Comment by AletaLabak** [comment]
Yeah, just tried the link you had in your note, Joe, and it's playing fine in the office. Also did a ctrl-shift-r to refresh, and it's still playing fine. Couldn't replicate the issue.

**Comment by freejoe76** [comment]
Okay, I changed the timing of the check-if-we-should-play-the-next-video functionality, let's see if that fixes things.

**Comment by freejoe76** [comment]
Looks like this is fixed.

**Comment by AletaLabak** [comment]
I'm not sure if this is happening because I'm trying to view from home, but when I play the new episode I'm experiencing same problem that happened with the very first episode. Is that happening for you as well?
http://dptv.denverpost.com/2015/03/27/cannabist-show-andrew-freedman-ean-seeb-interviews-marijuana-news/

**Comment by freejoe76** [comment]
I'm looking into this. I made some additional fixes yesterday to address this, but.... I didn't replicate the issue in Chrome, but I did see what you describe happen in the Firefox (flash) player. I've reopened this issue.

**Comment by freejoe76** [comment]
Ok, I did some research and made another change to the video script. Let me know if you see it again.

**Comment by AletaLabak** [comment]
I'm in office now, but....
When I try using this URL in Chrome and Firefox:
http://dptv.denverpost.com/2015/03/27/cannabist-show-andrew-freedman-ean-seeb-interviews-marijuana-news/

It's still not playing for me at all in Chrome, it's just flashing through
the URLs in queue.
When I tried Firefox, it plays the ad, then it loads next post in queue,
plays ad, then loads next post in queue, plays ad.
This is the video that eventually plays:
http://dptv.denverpost.com/2015/01/10/my-420-tours-provides-marijuana-education-experience-in-denver/



On Fri, Mar 27, 2015 at 12:30 PM, Joe Murphy <notifications@github.com>
wrote:

> Ok, I did some research and made another change to the video script. Let
> me know if you see it again.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/denverpost/dptv/issues/163#issuecomment-87044423>.
>



-- 
Aleta Labak
Online producer
The Cannabist <http://www.thecannabist.co/> // The Denver Post
<http://www.denverpost.com/>
101 W. Colfax, Suite 800
Denver, CO 80202
303.954.1327

**Comment by freejoe76** [comment]
Strangely, that My 420 Tours video was the video mine landed on too the time it cycled through them all.

**Comment by freejoe76** [comment]
This may be an ooyala issue. I just opened this ticket with them based on some new info I found:

>uncaught exception: Bad chunk: {"srcId":"cb7224e6-d4b2-11e4-b137-00259069bf72","srcKey":"11e4","srcStart":1427482511590,"replyTo":{"href":"http://dptv.denverpost.com/2015/03/13/the-cannabist-show-former-denver-broncos-te-nate-jackson-and-industry-insider-taylor-west/#dev","origin":"http://dptv.denverpost.com","protocol":"http:","username":"","password":"","host":"dptv.denverpost.com","hostname":"dptv.denverpost.com","port":"","pathname":"/2015/03/13/the-cannabist-show-former-denver-broncos-te-nate-jackson-and-industry-insider-taylor-west/","search":"","hash":"#dev"},"messageContent":{"self":{"position":[0],"pageId":"0","isMe":true,"isLeaf":false,"adProxies":[{"adId":"5689","adSafeId":"cb7224e6-d4b2-11e4-b137-00259069bf72"}],"unifiedId":1427482511590},"expectedPageId":"0-10","unifiedId":1427482511590,"sentTime":1427482511601},"srcIsEmbedded":false}


I> got it when our video player was moving from one video to the next using our in-house custom auto-play-next-video functionality. It would go to the next video, play the ad, then log that message to the console, then skip to the next video after that. http://dptv.denverpost.com/2015/03/11/the-cannabist-show-march-11-2015/#dev

**Comment by freejoe76** [comment]
Yea, it has something to do with the auto-play-next-video javascript I wrote, which doesn't exist on the Cannabist site.

**Comment by freejoe76** [comment]
Okay, I found another clue and put in another fix. Let's see if this works.

**Comment by AletaLabak** [comment]
Good/bad news: It played for me in Chrome! But I'm still having same
problems in Firefox. No ad played in Chrome, FYI.

On Fri, Mar 27, 2015 at 1:38 PM, Joe Murphy <notifications@github.com>
wrote:

> Okay, I found another clue and put in another fix. Let's see if this works.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/denverpost/dptv/issues/163#issuecomment-87067757>.
>



-- 
Aleta Labak
Online producer
The Cannabist <http://www.thecannabist.co/> // The Denver Post
<http://www.denverpost.com/>
101 W. Colfax, Suite 800
Denver, CO 80202
303.954.1327

**Comment by freejoe76** [comment]
Yea, I'm still digging.

**Comment by AletaLabak** [comment]
OK, I was mistaken that it was fixed in Chrome, anyway. I start with this
URL,
http://dptv.denverpost.com/2015/03/27/cannabist-show-andrew-freedman-ean-seeb-interviews-marijuana-news/

But this is the one that is actually playing:
http://dptv.denverpost.com/2015/03/13/the-cannabist-show-former-denver-broncos-te-nate-jackson-and-industry-insider-taylor-west/


On Fri, Mar 27, 2015 at 1:53 PM, Joe Murphy <notifications@github.com>
wrote:

> Yea, I'm still digging.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/denverpost/dptv/issues/163#issuecomment-87070888>.
>



-- 
Aleta Labak
Online producer
The Cannabist <http://www.thecannabist.co/> // The Denver Post
<http://www.denverpost.com/>
101 W. Colfax, Suite 800
Denver, CO 80202
303.954.1327

**Comment by freejoe76** [comment]
Okay I put in another couple fixes, can you clear your cache and try it again?

**Comment by AletaLabak** [comment]
Success! On both Chrome and Firefox. Thanks so much for your help, Joe!

On Fri, Mar 27, 2015 at 3:43 PM, Joe Murphy <notifications@github.com>
wrote:

> Okay I put in another couple fixes, can you clear your cache and try it
> again?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/denverpost/dptv/issues/163#issuecomment-87099922>.
>



-- 
Aleta Labak
Online producer
The Cannabist <http://www.thecannabist.co/> // The Denver Post
<http://www.denverpost.com/>
101 W. Colfax, Suite 800
Denver, CO 80202
303.954.1327

**Comment by freejoe76** [comment]
Super!
